// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG-l6g-inPgLQO8HfggXex7gTot0zK_is',
    appId: '1:836020710681:web:4b704d31ad69db9569e988',
    messagingSenderId: '836020710681',
    projectId: 'kcemaps',
    authDomain: 'kcemaps.firebaseapp.com',
    storageBucket: 'kcemaps.appspot.com',
    measurementId: 'G-MGXEP4QXB4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACooskeRdnl1N0252zJh5GxEpY1LTGLy4',
    appId: '1:836020710681:android:fbd2dd1d7cf8db3069e988',
    messagingSenderId: '836020710681',
    projectId: 'kcemaps',
    storageBucket: 'kcemaps.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9w7pZvl9-GxSn5dMouKaQOjLvVevGkVk',
    appId: '1:836020710681:ios:995b4f611179e14969e988',
    messagingSenderId: '836020710681',
    projectId: 'kcemaps',
    storageBucket: 'kcemaps.appspot.com',
    iosClientId: '836020710681-r0656ekkj67gi196vug4vtom4iut8op0.apps.googleusercontent.com',
    iosBundleId: 'com.example.kceMaps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9w7pZvl9-GxSn5dMouKaQOjLvVevGkVk',
    appId: '1:836020710681:ios:995b4f611179e14969e988',
    messagingSenderId: '836020710681',
    projectId: 'kcemaps',
    storageBucket: 'kcemaps.appspot.com',
    iosClientId: '836020710681-r0656ekkj67gi196vug4vtom4iut8op0.apps.googleusercontent.com',
    iosBundleId: 'com.example.kceMaps',
  );
}
